### ISSUE TITLE
Second `M.-` call does not expand to `xref-pop-marker-stack`

### ISSUE THREAD

**Issue by why-el** [thiagoa/rbtagger#39]
Hi Thiago, 

I am giving your project a go, and I really like its speed compared to others I tried in the past. I noticed though that the second `M.-` actually does not take me back to the original trigger point, like you state in the docs. When I do trigger `xref-pop-marker-stack` manually, it works. Is this a bug?

The second `M.` simply runs `xref-find-definitions`.

**Comment by thiagoa** [comment]
@why-el Sorry, I haven't been notified about this issue.

I think there's a typo in the docs; I will open a PR to fix it. The command should be: `M-,` (meta comma, and not meta dot), which should be the default Emacs keybinding for `xref-pop-marker-stack`. Please give it a try and let me know if it works for you :slightly_smiling_face: If not, you could map to whatever keybinding you prefer.

**Comment by thiagoa** [comment]
@why-el If I'm wrong and this is not a default Emacs keybinding, I could just add it to `rbtagger-mode-map`.

**Comment by thiagoa** [comment]
Fixed on #40

**Comment by why-el** [comment]
Works beautifully. Thank you @thiagoa. :)
