### ISSUE TITLE
problem with "bundle list --paths"

### ISSUE THREAD

**Issue by elphoton** [thiagoa/rbtagger#45]
Hello,

I've just installed your gem.

Problem : 

My bundle version output this line before gem paths list :

> Resolving dependencies...

It's break the parsing : ripper try to parse "Resolving" as a gem path

I've to replace 

>   'bundle list --paths' 

by 

>   'bundle list --paths | grep -v "Resolving dependencies...' 

in file 

>   ./bin/ruby_index_tags

my versions :

> ruby 2.7.1p83 (2020-03-31 revision a0c7c23c9c) [x86_64-linux-gnu]
> Bundler version 2.1.4   
> 

appart this little problem your gem work fine !

Thanks.

**Comment by thiagoa** [comment]
Hi @elphoton. Interesting, I'll take a look at that. It looks like notifications are being muted somehow for me, so I didn't notice your issue. Thank you for the heads up, I hope to come up with a solution soon! Also, feel free to open pull requests next time, or this time if you want to. Let me know anything.

**Comment by thiagoa** [comment]
@elphoton Are you sure no debug flag is turned on? I can't figure out how to reproduce the problem. I've tried with the same versions you mentioned. I opened a PR with a possible fix:

https://github.com/thiagoa/rbtagger/pull/47
